import 'data.dart';

/// Links to broadcaster-owned viewing pages. No streams are copied or proxied.
class TvChannel {
  final String id, name, city, country, type, url;
  final String? logoAsset;
  String get mapLabel => switch (id) {
    'a2' => 'A2',
    'ora' => 'ORA',
    'ktv' => 'KTV',
    'arta' => 'ARTA',
    'report-tv' => 'RTV',
    _ => name.length <= 5 ? name.toUpperCase() : 'TV',
  };
  const TvChannel(
    this.id,
    this.name,
    this.city,
    this.country,
    this.type,
    this.url, [
    this.logoAsset,
  ]);

  Event toEvent() {
    final location = cities.firstWhere(
      (candidate) => candidate.name == city && candidate.country == country,
    );
    return Event(
      id: 'tv-$id',
      title: name,
      description: 'Qyteti: $city\nLloji: $type',
      source: name,
      url: url,
      kind: 'tv',
      point: location.point,
    );
  }
}

const tvChannels = <TvChannel>[
  TvChannel(
    'rtsh',
    'RTSH',
    'Tiranë',
    'Shqipëri',
    'Publik',
    'https://tv.rtsh.al/',
    'assets/channel_logos/rtsh.jpg',
  ),
  TvChannel(
    'a2',
    'A2 CNN',
    'Tiranë',
    'Shqipëri',
    'Lajme',
    'https://a2news.com/live',
  ),
  TvChannel(
    'euronews-al',
    'Euronews Albania',
    'Tiranë',
    'Shqipëri',
    'Lajme',
    'https://euronews.al/live/',
    'assets/channel_logos/euronews-al.png',
  ),
  TvChannel(
    'news24',
    'News24',
    'Tiranë',
    'Shqipëri',
    'Lajme',
    'https://www.news24.al/livestream/',
    'assets/channel_logos/news24.png',
  ),
  TvChannel(
    'ora',
    'Ora News',
    'Tiranë',
    'Shqipëri',
    'Lajme',
    'https://oranews.tv/live/',
  ),
  TvChannel(
    'abc',
    'ABC News',
    'Tiranë',
    'Shqipëri',
    'Lajme',
    'https://abcnews.al/abcnews-live/',
    'assets/channel_logos/abc.png',
  ),
  TvChannel(
    'report-tv',
    'Report TV',
    'Tiranë',
    'Shqipëri',
    'Lajme',
    'https://live.report-tv.al/',
  ),
  TvChannel(
    'vizion-plus',
    'Vizion Plus',
    'Tiranë',
    'Shqipëri',
    'Gjeneralist',
    'https://www.vizionplus.tv/live/',
    'assets/channel_logos/vizion-plus.png',
  ),
  TvChannel(
    'klan-kosova',
    'Klan Kosova',
    'Prishtinë',
    'Kosovë',
    'Gjeneralist',
    'https://klankosova.tv/tv',
    'assets/channel_logos/klan-kosova.png',
  ),
  TvChannel(
    'rtk1',
    'RTK 1',
    'Prishtinë',
    'Kosovë',
    'Publik',
    'https://www.rtklive.com/sq/livestream/rtk1/',
  ),
  TvChannel(
    'rtk2',
    'RTK 2',
    'Prishtinë',
    'Kosovë',
    'Publik',
    'https://www.rtklive.com/sq/livestream/rtk2/',
  ),
  TvChannel(
    'rtk3',
    'RTK 3',
    'Prishtinë',
    'Kosovë',
    'Publik',
    'https://www.rtklive.com/sq/livestream/rtk3/',
  ),
  TvChannel(
    'rtk4',
    'RTK 4',
    'Prishtinë',
    'Kosovë',
    'Publik',
    'https://www.rtklive.com/sq/livestream/rtk4/',
  ),
  TvChannel(
    'ktv',
    'KTV',
    'Prishtinë',
    'Kosovë',
    'Lajme',
    'https://www.koha.net/',
  ),
  TvChannel(
    't7',
    'T7',
    'Prishtinë',
    'Kosovë',
    'Lajme',
    'https://www.televizioni7.com/live/',
    'assets/channel_logos/t7.png',
  ),
  TvChannel(
    'dukagjini',
    'RTV Dukagjini',
    'Pejë',
    'Kosovë',
    'Gjeneralist',
    'https://www.dukagjini.com/tv/',
    'assets/channel_logos/dukagjini.png',
  ),
  TvChannel(
    'arta',
    'Arta HD',
    'Prishtinë',
    'Kosovë',
    'Gjeneralist',
    'https://www.koha.net/',
  ),
  TvChannel(
    'tvcg1',
    'TVCG 1',
    'Podgoricë',
    'Mali i Zi',
    'Publik',
    'https://rtcg.me/tv/tv-uzivo.html',
    'assets/channel_logos/rtcg.png',
  ),
  TvChannel(
    'tvcg2',
    'TVCG 2',
    'Podgoricë',
    'Mali i Zi',
    'Publik',
    'https://rtcg.me/tv/tv-uzivo.html',
    'assets/channel_logos/rtcg.png',
  ),
  TvChannel(
    'tvcg3',
    'TVCG 3',
    'Podgoricë',
    'Mali i Zi',
    'Publik',
    'https://rtcg.me/tv/tv-uzivo.html',
    'assets/channel_logos/rtcg.png',
  ),
  TvChannel(
    'tvcgmne',
    'TVCG MNE',
    'Podgoricë',
    'Mali i Zi',
    'Publik',
    'https://rtcg.me/tv/tv-uzivo.html',
    'assets/channel_logos/rtcg.png',
  ),
  TvChannel(
    'tv7-me',
    'TV7',
    'Podgoricë',
    'Mali i Zi',
    'Gjeneralist',
    'https://www.televizija-tv7.me/uzivo.html',
    'assets/channel_logos/tv7-me.png',
  ),
  TvChannel(
    'etv-me',
    'E Televizija',
    'Podgoricë',
    'Mali i Zi',
    'Gjeneralist',
    'https://etv.me/',
  ),
  TvChannel(
    'mrt',
    'MRT',
    'Shkup',
    'Maqedonia e Veriut',
    'Publik',
    'https://play.mrt.com.mk/live/47',
    'assets/channel_logos/mrt.png',
  ),
  TvChannel(
    'alsat',
    'Alsat',
    'Shkup',
    'Maqedonia e Veriut',
    'Lajme',
    'https://alsat.mk/tv-alsat/',
  ),
  TvChannel(
    'tv21-mk',
    'TV21',
    'Shkup',
    'Maqedonia e Veriut',
    'Gjeneralist',
    'https://mk.tv21.tv/live-tv/',
    'assets/channel_logos/tv21-mk.png',
  ),
];
